# fly.toml app configuration file generated for steg-server on 2025-01-19T19:25:23-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'steg-server'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
